FROM oven/bun:1.3.9

WORKDIR /app

# Install dependencies for the monorepo
COPY package.json .
COPY packages ./packages
COPY apps ./apps
RUN bun install

# Move into the api app
WORKDIR /app/apps/api

EXPOSE 4000

ENV PORT=4000

# Run server (serves the Hono app)
CMD ["bun", "run", "src/index.ts"]