services:
  naiveform-api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - CONVEX_URL=https://adept-badger-863.convex.cloud
      - CLERK_WEBHOOK_SIGNING_SECRET=whsec_KvPHYy4GEQVzX8gj9qPO6dt5lxLO3HOx
      - SMTP_HOST=smtp.resend.com
      - SMTP_PORT=465
      - SMTP_USER=resend
      - SMTP_PASS=re_H2sKaowY_JzoUSQdFyMLeqaQtsTuNQz1F
      - SMTP_SECURE=true
      - EMAIL_FROM=naiveform-noreply@graphland.dev
    ports:
      - "4000:4000"
    restart: unless-stopped