/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplatesIndexRouteImport } from './routes/templates/index'
import { Route as FormsNewRouteImport } from './routes/forms/new'
import { Route as FormsFormIdRouteImport } from './routes/forms/$formId'
import { Route as FormsFormIdIndexRouteImport } from './routes/forms/$formId/index'
import { Route as FormsFormIdShareRouteImport } from './routes/forms/$formId/share'
import { Route as FormsFormIdSettingsRouteImport } from './routes/forms/$formId/settings'
import { Route as FormsFormIdResponsesRouteImport } from './routes/forms/$formId/responses'
import { Route as FormsFormIdPreviewRouteImport } from './routes/forms/$formId/preview'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplatesIndexRoute = TemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TemplatesRoute,
} as any)
const FormsNewRoute = FormsNewRouteImport.update({
  id: '/forms/new',
  path: '/forms/new',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdRoute = FormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsFormIdIndexRoute = FormsFormIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormsFormIdRoute,
} as any)
const FormsFormIdShareRoute = FormsFormIdShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => FormsFormIdRoute,
} as any)
const FormsFormIdSettingsRoute = FormsFormIdSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => FormsFormIdRoute,
} as any)
const FormsFormIdResponsesRoute = FormsFormIdResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => FormsFormIdRoute,
} as any)
const FormsFormIdPreviewRoute = FormsFormIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => FormsFormIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/forms/$formId': typeof FormsFormIdRouteWithChildren
  '/forms/new': typeof FormsNewRoute
  '/templates/': typeof TemplatesIndexRoute
  '/forms/$formId/preview': typeof FormsFormIdPreviewRoute
  '/forms/$formId/responses': typeof FormsFormIdResponsesRoute
  '/forms/$formId/settings': typeof FormsFormIdSettingsRoute
  '/forms/$formId/share': typeof FormsFormIdShareRoute
  '/forms/$formId/': typeof FormsFormIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/forms/new': typeof FormsNewRoute
  '/templates': typeof TemplatesIndexRoute
  '/forms/$formId/preview': typeof FormsFormIdPreviewRoute
  '/forms/$formId/responses': typeof FormsFormIdResponsesRoute
  '/forms/$formId/settings': typeof FormsFormIdSettingsRoute
  '/forms/$formId/share': typeof FormsFormIdShareRoute
  '/forms/$formId': typeof FormsFormIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/templates': typeof TemplatesRouteWithChildren
  '/forms/$formId': typeof FormsFormIdRouteWithChildren
  '/forms/new': typeof FormsNewRoute
  '/templates/': typeof TemplatesIndexRoute
  '/forms/$formId/preview': typeof FormsFormIdPreviewRoute
  '/forms/$formId/responses': typeof FormsFormIdResponsesRoute
  '/forms/$formId/settings': typeof FormsFormIdSettingsRoute
  '/forms/$formId/share': typeof FormsFormIdShareRoute
  '/forms/$formId/': typeof FormsFormIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/templates'
    | '/forms/$formId'
    | '/forms/new'
    | '/templates/'
    | '/forms/$formId/preview'
    | '/forms/$formId/responses'
    | '/forms/$formId/settings'
    | '/forms/$formId/share'
    | '/forms/$formId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/forms/new'
    | '/templates'
    | '/forms/$formId/preview'
    | '/forms/$formId/responses'
    | '/forms/$formId/settings'
    | '/forms/$formId/share'
    | '/forms/$formId'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/templates'
    | '/forms/$formId'
    | '/forms/new'
    | '/templates/'
    | '/forms/$formId/preview'
    | '/forms/$formId/responses'
    | '/forms/$formId/settings'
    | '/forms/$formId/share'
    | '/forms/$formId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  TemplatesRoute: typeof TemplatesRouteWithChildren
  FormsFormIdRoute: typeof FormsFormIdRouteWithChildren
  FormsNewRoute: typeof FormsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/templates/': {
      id: '/templates/'
      path: '/'
      fullPath: '/templates/'
      preLoaderRoute: typeof TemplatesIndexRouteImport
      parentRoute: typeof TemplatesRoute
    }
    '/forms/new': {
      id: '/forms/new'
      path: '/forms/new'
      fullPath: '/forms/new'
      preLoaderRoute: typeof FormsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId': {
      id: '/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof FormsFormIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/$formId/': {
      id: '/forms/$formId/'
      path: '/'
      fullPath: '/forms/$formId/'
      preLoaderRoute: typeof FormsFormIdIndexRouteImport
      parentRoute: typeof FormsFormIdRoute
    }
    '/forms/$formId/share': {
      id: '/forms/$formId/share'
      path: '/share'
      fullPath: '/forms/$formId/share'
      preLoaderRoute: typeof FormsFormIdShareRouteImport
      parentRoute: typeof FormsFormIdRoute
    }
    '/forms/$formId/settings': {
      id: '/forms/$formId/settings'
      path: '/settings'
      fullPath: '/forms/$formId/settings'
      preLoaderRoute: typeof FormsFormIdSettingsRouteImport
      parentRoute: typeof FormsFormIdRoute
    }
    '/forms/$formId/responses': {
      id: '/forms/$formId/responses'
      path: '/responses'
      fullPath: '/forms/$formId/responses'
      preLoaderRoute: typeof FormsFormIdResponsesRouteImport
      parentRoute: typeof FormsFormIdRoute
    }
    '/forms/$formId/preview': {
      id: '/forms/$formId/preview'
      path: '/preview'
      fullPath: '/forms/$formId/preview'
      preLoaderRoute: typeof FormsFormIdPreviewRouteImport
      parentRoute: typeof FormsFormIdRoute
    }
  }
}

interface TemplatesRouteChildren {
  TemplatesIndexRoute: typeof TemplatesIndexRoute
}

const TemplatesRouteChildren: TemplatesRouteChildren = {
  TemplatesIndexRoute: TemplatesIndexRoute,
}

const TemplatesRouteWithChildren = TemplatesRoute._addFileChildren(
  TemplatesRouteChildren,
)

interface FormsFormIdRouteChildren {
  FormsFormIdPreviewRoute: typeof FormsFormIdPreviewRoute
  FormsFormIdResponsesRoute: typeof FormsFormIdResponsesRoute
  FormsFormIdSettingsRoute: typeof FormsFormIdSettingsRoute
  FormsFormIdShareRoute: typeof FormsFormIdShareRoute
  FormsFormIdIndexRoute: typeof FormsFormIdIndexRoute
}

const FormsFormIdRouteChildren: FormsFormIdRouteChildren = {
  FormsFormIdPreviewRoute: FormsFormIdPreviewRoute,
  FormsFormIdResponsesRoute: FormsFormIdResponsesRoute,
  FormsFormIdSettingsRoute: FormsFormIdSettingsRoute,
  FormsFormIdShareRoute: FormsFormIdShareRoute,
  FormsFormIdIndexRoute: FormsFormIdIndexRoute,
}

const FormsFormIdRouteWithChildren = FormsFormIdRoute._addFileChildren(
  FormsFormIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  TemplatesRoute: TemplatesRouteWithChildren,
  FormsFormIdRoute: FormsFormIdRouteWithChildren,
  FormsNewRoute: FormsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
